### ISSUE TITLE
group.launch

### ISSUE THREAD

**Issue by puXiaoyi** [cloudwu/skynet_group#1]
`group.launch`中的`if`判断是否修改为`name_map[name] == nil`更为合适？

**Comment by cloudwu** [comment]
group.launch 并不限制同一名字服务只启动一次，如果需要只启动一次，可以用 group.query 。

**Comment by puXiaoyi** [comment]
云大，还是有些疑惑。

修改group_start和echoserver测试

```lua
local function init(id)
    print("Start group", id)
   
    local s1 = group.newservice("echoserver")
    print("s1 is", s1)
    -- print(group.call("echoserver", "echo", "hello"))
  
    local s2 = group.newservice("echoserver")
    print("s2 is", s2)
    print(group.call("echoserver", "echo", "hello")) 
end 
```

```lua
function echo.echo(...)
    return groupname, ..., skynet.self()
end
```

> result: 
   [:0000000b] LAUNCH snlua echoserver
Echo server in  GROUPA
s1 is   11
[:0000000c] LAUNCH snlua echoserver
Echo server in  GROUPA
s2 is   12
GROUPA  hello   12

从打印看，重复调用*group.newservice*会走*group.launch*中的*if*分支，*name_map*只会保存第二次创建服务的地址，这显然和*README*中*当同一个名字的服务被启动多份，后面启动的服务将没有名字，但 group.newservice返回的地址依然是有效的。*的描述不一致。当然如果在创建第一个服务后，就调用*group.call*发送消息，*group_service*会记录第一个服务的地址。即使再创建同名服务，调用*group.call*仍是向第一个服务发送消息。打开*init*方法代码中的第一个*print*的注释，两次打印的结果都会是 *GROUPA hello 11*。

所以我理解，*group.query*在名字服务存在时直接返回服务地址，否则，如果请求队列*launch_queue*为空，开始创建服务并初始化队列，创建过程的*query*请求放入*launch_queue*队列，创建完成后挂起的请求一并遍历返回。*group.launch*在名字服务不存在并且没有创建中的服务时，开始创建服务初始化队列，否则，直接创建服务，不会污染*name_map*，这样*name_map*只会保存第一次创建的名字服务。*if*的条件改成*launch_queue[name] == nil and name_map[name] == nil*是否更合适，这样name_map就不会被污染了，也符合*README*中*后面启动的服务将没有名字*的描述。不知道我有没有理解错云大的意思？

另外如果启动多份同名服务，暂不论*groupd*中*name_map*记录的是第一个还是最后一个地址，通过*group.call*或*group.send*传入*name*只能够向*name_map*匹配的一个地址发送消息，是不是*group.call*和*group.send*还是推荐传入地址数字参数？比如：
```lua
local function init(id)
    print("Start group", id)
   
    local s1 = group.newservice("echoserver")
    print("s1 is", s1)
    print(group.call(s1, "echo", "hello"))
  
    local s2 = group.newservice("echoserver")
    print("s2 is", s2)
    print(group.call(s2, "echo", "hello")) 
end 
```
> result: 
   [:0000000b] LAUNCH snlua echoserver
Echo server in  GROUPA
s1 is   11
GROUPA  hello   11
[:0000000c] LAUNCH snlua echoserver
Echo server in  GROUPA
s2 is   12
GROUPA  hello   12

我理解*group.launch*中*else*分支创建服务的代码是针对不同线程中启动多份服务，并且生成的服务拷贝不计入*services*统计。比如

```lua
local function init(id)
    print("Start group", id)
   
    skynet.fork(group.newservice, "echoserver")
    skynet.fork(group.newservice, "echoserver")
  
    skynet.sleep(0)
    print(group.call("echoserver", "echo", "hello"))
end 
```
> result: 
   [:0000000b] LAUNCH snlua echoserver
[:0000000c] LAUNCH snlua echoserver
Echo server in  GROUPA
Echo server in  GROUPA
GROUPA  hello   11

  打印的结果显示，第一个*newservice*走*if*分支，第二个*newservice*走*else*分支，*group.call*向第一个服务发送消息

不好意思，学习阶段，个人水平有限，写的啰里啰嗦，希望云大多指教。

**Comment by cloudwu** [comment]
当一个服务会被启动多份的时候，名字已经对它没有意义了。是否命名也不重要，这个时候你都应该用地址去访问它。

当一个服务只启动一次的时候，名字和它的地址是一一对应的。如果你的设计中知道这个服务只会启动一份，且希望用名字去访问它，那么你只应该用 group.query ，或直接在发送消息的时写名字，让框架去找到它，而不用关心它什么时候被启动的。

**Comment by cloudwu** [comment]
修改了 README 明确了 newservice 多个同名服务时，名字未定义；以及 query 会惰性初始化服务。

**Comment by puXiaoyi** [comment]
谢谢云大的回复
